version: '3.1'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AppPracticas

    ports:
      - ${PHP_PORT}:80

    volumes:
      - .:/var/www/html

    env_file:
      - .env
